version: '3'

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5400:5432
    env_file:
      - ./.env

volumes:
  db_data:
