version: '3'

services:
  local_db:
    image: postgres:13
    volumes:
      - local_db_data:/var/lib/postgresql/data
    ports:
      - 5400:5432
    env_file:
      - ./db_env.env

volumes:
  local_db_data:
